## camera calibration
-
-
-


### obtain the camera matrix

In [22]:
import numpy as np
import cv2
import glob

# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((7*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:7].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('*.jpg')

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (9,7),None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (9,7), corners2,ret)
        cv2.imshow('img',img)
        cv2.waitKey(2000)
        
cv2.destroyAllWindows()


ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)




### print the camera matrix

In [32]:
# print the camera matrix
print(mtx)


[[ 845.85589625    0.          291.79993605]
 [   0.          796.58787076  278.8003796 ]
 [   0.            0.            1.        ]]


In [24]:
type(mtx)

numpy.ndarray

### convert camera matrix from array to dict 

In [25]:
mtx_dict = dict(enumerate(mtx.flatten(), 1))
print(m)

{1: 845.85589625293278, 2: 0.0, 3: 291.79993605092363, 4: 0.0, 5: 796.58787076147109, 6: 278.80037960002295, 7: 0.0, 8: 0.0, 9: 1.0}


### generate yaml document

In [26]:
import yaml

with open('mtx_test.yml', 'w') as outfile:
    yaml.dump(mtx_dict, outfile, default_flow_style=False)
f = open('mtx_test.yml')
x = yaml.load(f)
print(x)
    

### define the matx_get function to get matrix from yaml document 

**warning:**

  wrong format of output
  
**code**
```py
    print('camera_matrix \n',cam)
    print('distortion_coefficients \n',dis)
    print('projection_matrix \n',pro)
    print('rectification_matrix \n',rec)
```
**output**
```py
('camera_matrix \n', matrix([[  2.30259000e+03,   0.00000000e+00,   6.10756000e+02],
        [  0.00000000e+00,   2.30946000e+03,   5.06539000e+02],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]]))
('distortion_coefficients \n', matrix([[ -2.25495000e-01,  -3.63048000e-01,  -4.77994000e-04,
          -1.32753000e-04,   0.00000000e+00]]))
('projection_matrix \n', matrix([[  2.30259000e+03,   0.00000000e+00,   6.10756000e+02,
           0.00000000e+00],
        [  0.00000000e+00,   2.30946000e+03,   5.06539000e+02,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
           0.00000000e+00]]))
('rectification_matrix \n', matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]))
```


In [29]:
file_name = ('camera_matrix.yaml')

In [33]:
import yaml
import numpy as np

def matx_get(file_name):
    f = open(file_name)
    mtrx = yaml.load(f)
    
    cam = np.matrix(mtrx['camera_matrix']['data']).reshape(3,3)
    dis = np.matrix(mtrx['distortion_coefficients']['data']).reshape(1,5) 
    pro = np.matrix(mtrx['projection_matrix']['data']).reshape(3,4)
    rec = np.matrix(mtrx['rectification_matrix']['data']).reshape(3,3)
    
    print("camera_matrix:  \n {}".format(cam))
    print("distortion_coefficients:  \n {}".format(dis))
    print("projection_matrix:  \n {}".format(pro))
    print("rectification_matrix:  \n {}".format(rec))

matx_get('camera_matrix.yaml')   

camera_matrix:  
 [[  2.30259000e+03   0.00000000e+00   6.10756000e+02]
 [  0.00000000e+00   2.30946000e+03   5.06539000e+02]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]
distortion_coefficients:  
 [[ -2.25495000e-01  -3.63048000e-01  -4.77994000e-04  -1.32753000e-04
    0.00000000e+00]]
projection_matrix:  
 [[  2.30259000e+03   0.00000000e+00   6.10756000e+02   0.00000000e+00]
 [  0.00000000e+00   2.30946000e+03   5.06539000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00]]
rectification_matrix:  
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


### using undistort

In [7]:
#using undistort
img = cv2.imread('chess08.jpg')
h,  w = img.shape[:2]
newcameramtx, roi=cv2.getOptimalNewCameraMatrix(mtx,dist,(w,h),1,(w,h))

# undistort
dst = cv2.undistort(img, mtx, dist, None, newcameramtx)

# crop the image
x,y,w,h = roi
dst = dst[y:y+h, x:x+w]
cv2.imwrite('calibresult1.png',dst)

True

### using remaping

In [13]:
#using remaping
# undistort
mapx,mapy = cv2.initUndistortRectifyMap(mtx,dist,None,newcameramtx,(w,h),5)
dst = cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)

# crop the image
x,y,w,h = roi
dst = dst[y:y+h, x:x+w]
cv2.imwrite('calibresult2.png',dst)

True

### calculate error

In [8]:
mean_error = 0
tot_error =0
for i in range(len(objpoints)):
    imgpoints2, _ = cv2.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
    error = cv2.norm(imgpoints[i],imgpoints2, cv2.NORM_L2)/len(imgpoints2)
    tot_error += error
    print("tot_error %f"%(tot_error))

    
print ("total error: %f"%(tot_error/len(objpoints)))

tot_error 0.109478
tot_error 0.233759
tot_error 0.318128
tot_error 0.390566
tot_error 0.483587
tot_error 0.561234
tot_error 0.674374
tot_error 0.762033
tot_error 0.837495
tot_error 0.911084
tot_error 1.005607
tot_error 1.139577
tot_error 1.233083
tot_error 1.292589
total error: 0.092328
